/* generado por tools/add_pc.py: animaciones del PvZ de PC (indices de pista y rangos de frames) */
#ifndef PC_ANIMS_H
#define PC_ANIMS_H
#define RE_PC_FIRST 108

#define RE_PC_SPLITPEA 108   /* SplitPea.reanim: 22 pistas, 132 frames, 12 fps */
#define PC_SPLITPEA_T_BACKLEAF 0
#define PC_SPLITPEA_T_BACKLEAF_LEFT_TIP 1
#define PC_SPLITPEA_T_BACKLEAF_RIGHT_TIP 2
#define PC_SPLITPEA_T_STALK_BOTTOM 3
#define PC_SPLITPEA_T_STALK_TOP 4
#define PC_SPLITPEA_T_FRONTLEAF 5
#define PC_SPLITPEA_T_FRONTLEAF_RIGHT_TIP 6
#define PC_SPLITPEA_T_FRONTLEAF_TIP_LEFT 7
#define PC_SPLITPEA_T_ANIM_IDLE 8
#define PC_SPLITPEA_ANIM_IDLE_S 7
#define PC_SPLITPEA_ANIM_IDLE_E 31
#define PC_SPLITPEA_T_ANIM_SHOOTING 9
#define PC_SPLITPEA_ANIM_SHOOTING_S 107
#define PC_SPLITPEA_ANIM_SHOOTING_E 131
#define PC_SPLITPEA_T_ANIM_HEAD_IDLE 10
#define PC_SPLITPEA_ANIM_HEAD_IDLE_S 82
#define PC_SPLITPEA_ANIM_HEAD_IDLE_E 106
#define PC_SPLITPEA_T_ANIM_FACE 11
#define PC_SPLITPEA_T_IDLE_MOUTH 12
#define PC_SPLITPEA_T_ANIM_SPLITPEA_IDLE 13
#define PC_SPLITPEA_ANIM_SPLITPEA_IDLE_S 32
#define PC_SPLITPEA_ANIM_SPLITPEA_IDLE_E 56
#define PC_SPLITPEA_T_ANIM_SPLITPEA_SHOOTING 14
#define PC_SPLITPEA_ANIM_SPLITPEA_SHOOTING_S 57
#define PC_SPLITPEA_ANIM_SPLITPEA_SHOOTING_E 69
#define PC_SPLITPEA_T_SPLITPEA_HEAD 15
#define PC_SPLITPEA_T_SPLITPEA_MOUTH 16
#define PC_SPLITPEA_T_IDLE_SHOOT_BLINK 17
#define PC_SPLITPEA_T_IDLE_SPLITPEA_SHOOT_BLINK 18
#define PC_SPLITPEA_T_ANIM_BLINK 19
#define PC_SPLITPEA_T_ANIM_SPLITPEA_BLINK 20
#define PC_SPLITPEA_T_SPLITPEA_EYEBROWS 21

#define RE_PC_GLOOMSHROOM 109   /* GloomShroom.reanim: 21 pistas, 71 frames, 12 fps */
#define PC_GLOOMSHROOM_T_ANIM_BLINK 0
#define PC_GLOOMSHROOM_ANIM_BLINK_S 0
#define PC_GLOOMSHROOM_ANIM_BLINK_E 4
#define PC_GLOOMSHROOM_T_ANIM_IDLE 1
#define PC_GLOOMSHROOM_ANIM_IDLE_S 5
#define PC_GLOOMSHROOM_ANIM_IDLE_E 23
#define PC_GLOOMSHROOM_T_ANIM_SLEEP 2
#define PC_GLOOMSHROOM_ANIM_SLEEP_S 24
#define PC_GLOOMSHROOM_ANIM_SLEEP_E 42
#define PC_GLOOMSHROOM_T_ANIM_SHOOTING 3
#define PC_GLOOMSHROOM_ANIM_SHOOTING_S 43
#define PC_GLOOMSHROOM_ANIM_SHOOTING_E 70
#define PC_GLOOMSHROOM_T_GLOOMSHROOM_BASE 4
#define PC_GLOOMSHROOM_T_GLOOMSHROOM_SHOOTER4 5
#define PC_GLOOMSHROOM_T_GLOOMSHROOM_SHOOTER42 6
#define PC_GLOOMSHROOM_T_GLOOMSHROOM_SHOOTER5 7
#define PC_GLOOMSHROOM_T_ANIM_FACE 8
#define PC_GLOOMSHROOM_T_GLOOMSHROOM_STEM1 9
#define PC_GLOOMSHROOM_T_GLOOMSHROOM_SHOOTER1 10
#define PC_GLOOMSHROOM_T_GLOOMSHROOM_STEM2 11
#define PC_GLOOMSHROOM_T_GLOOMSHROOM_STEM22 12
#define PC_GLOOMSHROOM_T_GLOOMSHROOM_SHOOTER2 13
#define PC_GLOOMSHROOM_T_GLOOMSHROOM_SHOOTER22 14
#define PC_GLOOMSHROOM_T_GLOOMSHROOM_STEM3 15
#define PC_GLOOMSHROOM_T_GLOOMSHROOM_STEM32 16
#define PC_GLOOMSHROOM_T_GLOOMSHROOM_SHOOTER3 17
#define PC_GLOOMSHROOM_T_GLOOMSHROOM_SHOOTER32 18
#define PC_GLOOMSHROOM_T_GLOOMSHROOM_FACE 19
#define PC_GLOOMSHROOM_T_BLINK 20

#define RE_PC_COFFEEBEAN 110   /* Coffeebean.reanim: 5 pistas, 29 frames, 12 fps */
#define PC_COFFEEBEAN_T_ANIM_IDLE 0
#define PC_COFFEEBEAN_ANIM_IDLE_S 0
#define PC_COFFEEBEAN_ANIM_IDLE_E 8
#define PC_COFFEEBEAN_T_ANIM_TWITCH 1
#define PC_COFFEEBEAN_ANIM_TWITCH_S 9
#define PC_COFFEEBEAN_ANIM_TWITCH_E 13
#define PC_COFFEEBEAN_T_ANIM_CRUMBLE 2
#define PC_COFFEEBEAN_ANIM_CRUMBLE_S 14
#define PC_COFFEEBEAN_ANIM_CRUMBLE_E 28
#define PC_COFFEEBEAN_T_COFFEEBEAN_LEAF 3
#define PC_COFFEEBEAN_T_COFFEEBEAN_HEAD 4
#define RE_PC_COUNT 111
#endif
