/* generado por tools/add_pc.py: animaciones del PvZ de PC (indices de pista y rangos de frames) */
#ifndef PC_ANIMS_H
#define PC_ANIMS_H
#define RE_PC_FIRST 108

#define RE_PC_SPLITPEA 108   /* SplitPea.reanim: 22 pistas, 132 frames, 12 fps */
#define PC_SPLITPEA_T_BACKLEAF 0
#define PC_SPLITPEA_T_BACKLEAF_LEFT_TIP 1
#define PC_SPLITPEA_T_BACKLEAF_RIGHT_TIP 2
#define PC_SPLITPEA_T_STALK_BOTTOM 3
#define PC_SPLITPEA_T_STALK_TOP 4
#define PC_SPLITPEA_T_FRONTLEAF 5
#define PC_SPLITPEA_T_FRONTLEAF_RIGHT_TIP 6
#define PC_SPLITPEA_T_FRONTLEAF_TIP_LEFT 7
#define PC_SPLITPEA_T_ANIM_IDLE 8
#define PC_SPLITPEA_ANIM_IDLE_S 7
#define PC_SPLITPEA_ANIM_IDLE_E 31
#define PC_SPLITPEA_T_ANIM_SHOOTING 9
#define PC_SPLITPEA_ANIM_SHOOTING_S 107
#define PC_SPLITPEA_ANIM_SHOOTING_E 131
#define PC_SPLITPEA_T_ANIM_HEAD_IDLE 10
#define PC_SPLITPEA_ANIM_HEAD_IDLE_S 82
#define PC_SPLITPEA_ANIM_HEAD_IDLE_E 106
#define PC_SPLITPEA_T_ANIM_FACE 11
#define PC_SPLITPEA_T_IDLE_MOUTH 12
#define PC_SPLITPEA_T_ANIM_SPLITPEA_IDLE 13
#define PC_SPLITPEA_ANIM_SPLITPEA_IDLE_S 32
#define PC_SPLITPEA_ANIM_SPLITPEA_IDLE_E 56
#define PC_SPLITPEA_T_ANIM_SPLITPEA_SHOOTING 14
#define PC_SPLITPEA_ANIM_SPLITPEA_SHOOTING_S 57
#define PC_SPLITPEA_ANIM_SPLITPEA_SHOOTING_E 69
#define PC_SPLITPEA_T_SPLITPEA_HEAD 15
#define PC_SPLITPEA_T_SPLITPEA_MOUTH 16
#define PC_SPLITPEA_T_IDLE_SHOOT_BLINK 17
#define PC_SPLITPEA_T_IDLE_SPLITPEA_SHOOT_BLINK 18
#define PC_SPLITPEA_T_ANIM_BLINK 19
#define PC_SPLITPEA_T_ANIM_SPLITPEA_BLINK 20
#define PC_SPLITPEA_T_SPLITPEA_EYEBROWS 21
#define RE_PC_COUNT 109
#endif
